=== katri-lantto/arg/src/json/schemas/HomeSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/HomeSchema",
    "definitions": {
        "HomeSchema": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "passphrase": {
                    "type": "string",
                    "format": "integer"
                },
                "encrypted_email": {
                    "type": "string"
                },
                "header_title": {
                    "type": "string"
                },
                "first_paragraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "second_paragraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "third_paragraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "fourth_paragraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "images": {
                    "$ref": "#/definitions/Images"
                }
            },
            "required": [
                "passphrase",
                "encrypted_email",
                "first_paragraph",
                "second_paragraph",
                "third_paragraph",
                "fourth_paragraph",
                "header_title",
                "images"
            ]
        },
        "Paragraph": {
            "title": "Paragraph",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "image": {
                    "$ref": "#/definitions/Image"
                }
            },
            "required": [
                "title",
                "text"
            ]
        },
        "Images": {
            "title": "Images",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "header": {
                    "$ref": "#/definitions/Image"
                },
                "techImages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Image"
                    }
                }
            },
            "required": [
                "header",
                "techImages"
            ]
        },
        "Image": {
            "title": "Image",
            "type": "string",
            "oneOf": [{"pattern": "^img/.{0,}\\.jpg$"},
                      {"pattern": "^img/.{0,}\\.png$"}]
        }
    }
}

=== katri-lantto/arg/src/json/Home.json
{          
  "passphrase": "3121",
  "encrypted_email": "087 105 108 102 114 101 100 077 097 108 109 050 056 053 064 103 109 097 105 108 046 099 111 109",
  "header_title": "Difax",
  "first_paragraph": { 
        "title": "What we do",
        "text": "We combine the latest AI and surveillance technology to provide our customers with the highest levels of security. We start by setting up equipment around your area which then connects to our servers here at Difax. This equipment lets us monitor and observe potential threats against you or your company. If a threat is deemed actionable our elite security guards will be at your location before the perpetrators can do anything.",
        "image": "img/intro-img.jpg"
  },
  "second_paragraph": {
        "title": "Why choose us?",
        "text": "Our customers safety is our top priority and we have the data to back it up. All attempted robberies of our customers, since our launch in 1998, have either been stopped or the people involved have been caught and prosecuted. In either situation our customers have been able to claim insurance leaving them in a beneficial situation. Our unique technology allows for methods of identification that no other company possesses. We also use advanced behavioural methods that let us predict dangerous situations ahead of time."
  },
  "third_paragraph": {
        "title": "How does AI integrate with surveillance?",
        "text": "Artificial intelligence is complicated but our engineers here at Difax have come up with a method of collaboration that lets our technology utilize AI to analyze captured footage. This analysis lets us know if there is any unusual activity going on and if we should act upon it."
  },
  "fourth_paragraph": {
        "title": "Indirect Protection",
        "text": "Companies that fly our banner have noticed a steady decrease in crime ever since they partnered with us. The results speak for themselves. Criminals are starting to become aware of our success rate and no longer willing to take the risk of going against us. As our reputation grows crime rates fall and will continue to fall."
  },
  "images": {
        "header": "img/header.png",
        "techImages": [
              "img/homepage-img1.jpg",
              "img/homepage-img2.jpg",
              "img/homepage-img3.jpg"
            ]
      }
}
