=== katri-lantto/arg/src/json/schemas/OurWorkSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/OurWork",
    "definitions": {
        "OurWork": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "puzzleVar": {
                    "type": "string",
                    "format": "integer"
                },
                "username": {
                    "type": "string"
                },
                "headerTitle": {
                    "type": "string"
                },
                "firstParagraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "secondParagraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "thirdParagraph": {
                    "$ref": "#/definitions/Paragraph"
                },
                "images": {
                    "$ref": "#/definitions/Images"
                }
            },
            "required": [
                "firstParagraph",
                "headerTitle",
                "images",
                "puzzleVar",
                "secondParagraph",
                "thirdParagraph",
                "username"
            ],
            "title": "OurWork"
        },
        "Paragraph": {
            "title": "FirstParagraph",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "image": {
                    "$ref": "#/definitions/Image"
                }
            },
            "required": [
                "title",
                "text"
            ]
        },
        "Images": {
            "title": "Images",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "header": {
                    "$ref": "#/definitions/Image"
                },
                "slideImages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Image"
                    }
                },
                "futurePlans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Image"
                    }
                }
            },
            "required": [
                "header",
                "slideImages",
                "futurePlans"
            ]
        },
        "Image": {
            "title": "Image",
            "type": "string",
            "oneOf": [{"pattern": "^img/.{0,}\\.jpg$"},
                      {"pattern": "^img/.{0,}\\.png$"}]
        }
    }
}

=== katri-lantto/arg/src/json/OurWork.json
{
  "puzzleVar": "14253",
  "username": "Edmund_Schmidt",
  "headerTitle": "Our Work",
  "firstParagraph": { 
        "title": "Current work",
        "text": "Our team of engineers are not only working on new ways to improve security but also finding methods in which customers can be more active in their own security. One of these ongoing projects aims to provide detailed information and visuals summarizing activity in and around their area on a weekly or monthly basis. We believe this will provide the customer with a sense of calm, reassuring them that their business is safe while out on a holiday.",
        "image": "img/interaction.jpg"
  },
  
  "secondParagraph": {
        "title": "What we have done",
        "text": "We have created applications across multiple platforms (smartphones, computers and smart watches) that allow customers to access their security cameras wherever they may be. We use unique technologies such as patrolling drones capable of dynamic automated security unlike any normal camera is able to do. However impressive these technologies may sound, our true ‘ace up the sleeve’ lies in our software, our Artificial Intelligence. "
  },
  "thirdParagraph": {
        "title": "Future Work",
        "text": "For future work we want to continue expanding on the technologies we already have and develop new methods of surveillance unlike any that exist today. Our engineers have expressed interest in ideas such as linking up our systems to the customers doors, elevators, computer hardware and wireless systems. We believe this will help us achieve our dream of a 0% crime rate."
  },
  "images": {
      "header":  "img/work-header.jpg",
      "slideImages":  [
            "img/slide-image-1.jpg",
            "img/slide-image-2.jpg",
            "img/slide-image-3.jpg",
            "img/slide-image-4.jpg",
            "img/slide-image-5.jpg"],
      "futurePlans": [
            "img/future-ai.jpg",
            "img/robotic-future.jpg",
            "img/future-security.jpg"
      ]
  }
}
